version: '3.7'

services:
  nuxt:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nuxt
    restart: always
    ports:
      - "3001:3000"
    # Replace with your Nuxt.js start command
    # command: "npm run start"
    command: "node /app/.output/server/index.mjs"
